### ISSUE TITLE
Install extensions postgis, postgis_topology, postgis_tiger_geocoder

### ISSUE THREAD

**Issue by phlegx** [rgeo/activerecord-postgis-adapter#118]
I'm not able to install postgis, postgis_topology, postgis_tiger_geocoder this extensions. I use this database config:

``` yaml
development:
  adapter: postgis
  ...
  schema_search_path: 'public,postgis,topology,tiger'
  postgis_extension: 'postgis,postgis_topology,postgis_tiger_geocoder'
  postgis_sql_path: /usr/pgsql-9.3/share/contrib/postgis-2.1
```

I get this error:

```
PG::FeatureNotSupported: ERROR:  extension "postgis_tiger_geocoder" must be installed in schema "tiger"
: CREATE EXTENSION postgis_tiger_geocoder SCHEMA postgis
```

Postgis recommends this installation for postgis 2.1:
http://postgis.net/docs/postgis_installation.html

```
psql -d yourdatabase -c "CREATE EXTENSION postgis;"
psql -d yourdatabase -c "CREATE EXTENSION postgis_topology;"
psql -d yourdatabase -c "CREATE EXTENSION postgis_tiger_geocoder;"
```

My database supports this extensions:

```
postgres=# SELECT name, default_version,installed_version 
postgres-# FROM pg_available_extensions WHERE name LIKE 'postgis%' ;
          name          | default_version | installed_version 
------------------------+-----------------+-------------------
 postgis_topology       | 2.1.3           | 
 postgis_tiger_geocoder | 2.1.3           | 
 postgis                | 2.1.3           | 
```

Any idea?
