### ISSUE TITLE
why i get this error "PG::ConnectionBad: fe_sendauth: no password supplied" in vps?

### ISSUE THREAD

**Issue by 85636682** [rgeo/activerecord-postgis-adapter#136]
i run this 

```
bundle exec rake db:gis:setup
```

i get this error:

```
rake aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
```

database.yml

```
production:
  encoding: utf8
  adapter: postgis
  database: dongqilai
  pool: 5
  timeout: 5000
  username: stephen
  password: 861117900331hs
  su_username: postgres     # a superuser for the database
  su_password: 861117900331hs  # the superuser's password
  host: localhost
  schema_search_path: public
```

pg_hba.conf

```
# Database administrative login by Unix domain socket
local   all             postgres                                md5

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```
