### ISSUE TITLE
rake db:gis:setup with `role "deploy" does not exist`

### ISSUE THREAD

**Issue by TangMonk** [rgeo/activerecord-postgis-adapter#205]
I am running command for user `deploy` with command `rake db:gis:setup`, but throw me an error:

```
ActiveRecord::NoDatabaseError: FATAL:  role "deploy" does not exist
/var/www/rails/youleyuan/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:665:in `rescue in connect'
/var/www/rails/youleyuan/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
/var/www/rails/youleyuan/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/var/www/rails/youleyuan/vendor/bundle/ruby/2.1.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis_adapter.rb:51:in `initialize'
/var/www/rails/youleyuan/vendor/bundle/ruby/2.1.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/create_connection.rb:37:in `new'
/var/www/rails/youleyuan/vendor/bundle/ruby/2.1.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/create_connection.rb:37:in `postgis_connection'
```

my database config file:

```
default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
  password: 123
  host: localhost
  database: youleyuan_development
```
