### ISSUE TITLE
How to set up for Heroku deployment?

### ISSUE THREAD

**Issue by bifork** [rgeo/activerecord-postgis-adapter#240]
## I have the following:

Initializer: config/initializers/rgeo.rb
```
require 'rgeo-activerecord'

RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  # By default, use the GEOS implementation for spatial columns.
  config.default = RGeo::Geos.factory_generator

  # But use a geographic implementation for point columns.
  config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "point")
end
```

Database settings: config/database.yml
```
default: &default
  adapter: postgis
  encoding: unicode
  username: unfold_u
  password: password
  su_username: unfold_su
  su_password: Pa55w0rd
  schema_search_path: "public, postgis"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: unfold_development
  script_dir: /usr/local/opt/postgis/share/postgis
test:
  <<: *default
  database: unfold_test
  script_dir: /usr/local/opt/postgis/share/postgis

production:
  <<: *default
  database: unfold_production
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  username: unfold
  password: <%= ENV['UNFOLD_DATABASE_PASSWORD'] %>
```

Enable postgis extension of heroku postgresql:
```
$ heroku pg:psql --app ngrails-unfold
> CREATE EXTENSION postgis;
> select postgis_version();
            postgis_version            
---------------------------------------
 2.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```

Data model migration:
```
class CreateLocations < ActiveRecord::Migration[5.0]
  def change
    create_table :locations do |t|
      t.string :name, null: false
      t.st_point :latlon, geographic: true, null: false

      t.timestamps
    end

    add_index :locations, :name
  end
end
```

Build packs:
1. Possibly a frontend app buildpack
2. https://github.com/cyberdelia/heroku-geo-buildpack.git Or https://github.com/desaperados/heroku-buildpack-geo.git 
3. heroku/ruby

## But I still get error: 
NoMethodError (undefined method `property' for nil:NilClass)
——— Logs ———
```
heroku[router]: at=info method=POST path="/api/locations.json" host=ngrails-unfold.herokuapp.com request_id=4053b701-9d3e-479c-8a33-c44e539ccdc8 fwd="45.63.35.55" dyno=web.1 connect=3ms service=28ms status=500 bytes=551

Started POST "/api/locations.json" for 45.63.35.55 at 2016-11-15 14:36:41 +0000

Processing by LocationsController#create as JSON

Parameters: {"location"=>{"name"=>"San Francisco Airport", "latlon"=>"POINT(-122.381827 37.62161)"}}

BEGIN

Location Exists (1.7ms)  SELECT  1 AS one FROM "locations" WHERE "locations"."name" = $1 LIMIT $2  [["name", "San Francisco Airport"], ["LIMIT", 1]]
```
——— Error logs from heroku ———
```
ROLLBACK

Completed 500 Internal Server Error in 15ms (ActiveRecord: 6.1ms)

NoMethodError (undefined method `property' for nil:NilClass):

app/controllers/locations_controller.rb:20:in `create'
```
——— Success logs from localhost ———-
```
INSERT INTO "locations" ("name", "latlon", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "San Francisco Airport"], ["latlon", "0020000001000010e6c05e986fda836eb54042cf90ea9e6eeb"], ["created_at", 2016-11-15 14:35:29 UTC], ["updated_at", 2016-11-15 14:35:29 UTC]]

COMMIT
```

So what are the correct steps to set up a postgis-adaptered Rails app on Heroku?
