### ISSUE TITLE
"PG::UndefinedFile: ERROR:  could not open extension control file" when creating DB

### ISSUE THREAD

**Issue by Croge32** [rgeo/activerecord-postgis-adapter#288]
So I've set up the database according to the README regarding installation of the gem and adjusting the database.yml file. I also installed postgis via Homebrew as well as downloaded the Postgres.app.

I'm getting this issue when I either run `rails db:create` or `rails db:gis:setup`:

```
PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS postgis
Couldn't create database for {"adapter"=>"postgis", "database"=>"db_name", "encoding"=>"utf8", "username"=>"postgres", "password"=>nil, "host"=>"db", "min_messages"=>"warning", "pool"=>5, "reaping_frequency"=>10, "timeout"=>5000}
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory
```

My database.yml:

```
development: &default
  adapter: postgis
  database: db_name
  encoding: utf8
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password:
  host: <%= ENV.fetch("DB_HOST") %>
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: db_name

production: &deploy
  <<: *default
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
```

Any idea where the issue is in my setup? Seems like maybe I don't have PostGis installed properly? This app/database lives on a docker container as well, if that's relevant or requires some special setup.
