### ISSUE TITLE
Geometry Columns does not exist

### ISSUE THREAD

**Issue by tomciopp** [rgeo/activerecord-postgis-adapter#29]
I have followed your talk from railsconf 2012 and I am running into a few errors when trying to implement the second example on looking up timezones based on a location. The details of my setup are as follows: I am running Postgresql using [Postgres.app](http://postgresapp.com/documentation) which gives me version 9.1.3 of Postgres and 2.0.0 of PostGIS. I run into a few issues with the database.yml file, and running migrations. ( I have added the relevant gems and required their info in application.rb)

My database.yml file looks like this:

```
 development:
   adapter: postgis
   postgis_extension: true
   host: localhost
   encoding: unicode
   database: my_app_development
   pool: 5
   username: my_app
   password:
```

If I add the following line `schema_search_path: "public,postgis"` I get:

```
 rake aborted!
 PG::Error: ERROR:  schema "postgis" does not exist
 : SET search_path TO public,postgis
```

If I remove that line I receive the following error when I try to migrate my database:

```
rake aborted!
PG::Error: ERROR:  relation "geometry_columns" does not exist
LINE 1: SELECT * FROM geometry_columns WHERE f_table_name='schema_mi...                       ^
: SELECT * FROM geometry_columns WHERE f_table_name='schema_migrations'
```

Do you have any idea how to fix these issues, or what is causing them to occur?
