### ISSUE TITLE
db:create not working on branch bump-7-2

### ISSUE THREAD

**Issue by dorner** [rgeo/activerecord-postgis-adapter#415]
When I try running `rake db:create`, I get the following error:

```
ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'postgis' adapter (ActiveRecord::Tasks::DatabaseNotSupported)
```

If I add this in an initializer, it works:

`ActiveRecord::Tasks::DatabaseTasks.register_task(/postgis/, "ActiveRecord::Tasks::PostgreSQLDatabaseTasks")`

Not sure if this is something that used to be handled automatically and no longer is with Rails 7.2. I can whip up a PR if y'all like, just wanted to double check if I was doing something wrong.

**Comment by BuonOmo** [comment]
Yep, open a PR!

**Comment by keithdoggett** [comment]
@dorner we used to have a test for tasks in older versions. This PR removed the deprecated tasks, but this is the file we used to test them: https://github.com/rgeo/activerecord-postgis-adapter/pull/353/files#diff-7b02d5d1111ed5b54c5fe75fb4796e01b12d15ba0db38212fb628f8516e379a4. That should be a sufficient structure to test this on.

**Comment by keithdoggett** [comment]
Actually, @dorner it appears this is already in the branch: https://github.com/rgeo/activerecord-postgis-adapter/blob/435027dec04898d9e2f840652f1e19b236e55f8e/lib/active_record/connection_adapters/postgis_adapter.rb#L163. Not sure why it's not working as expected though.

**Comment by dorner** [comment]
Ah good catch! I'll do some spelunking to see if there's a loading issue. I'll try to bring back that file just to test this for backwards compability with existing Rails tasks.

**Comment by keithdoggett** [comment]
Hey @dorner I just made a new rails app and was able to run `db:create` from the 7.2 branch. Are you seeing that issue as well or is this occurring on an existing app?

**Comment by dorner** [comment]
Tried this again and it seems to be working. No idea what happened before. Closing this, will reopen if I figure out anything else :)

**Comment by dorner** [comment]
OK interesting. `rails db:reset` works but `rails db:create` does not.

**Comment by dorner** [comment]
Yup. Looks like the `PostgisAdapter` file is not loaded on `db:create` since it's first loaded when a connection is attempted. `db:create` doesn't attempt a connection before running.

I'm wondering if something else in your new app is "accidentally" creating a connection and hence the adapter registration happens.

The code itself is super easy (just add the register call to the very base Ruby file). The test file you linked doesn't really help because it calls the database module directly - the whole issue here seems to be related to a loading problem. Would it be OK to put in a PR without a corresponding test?

**Comment by keithdoggett** [comment]
@dorner I think that's fine since it's just a loading issue

**Comment by dorner** [comment]
PR is up! #418

**Comment by dorner** [comment]
Got the problem! The issue is happening only when there are multiple databases, and a _secondary_ database is postgis.

Using this database.yml:

```yaml
development:
  primary:
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['DB_DATABASE'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: '<%= ENV['DB_PASSWORD'] %>'
    adapter: trilogy
    port: 3306
  other:
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['DB_DATABASE'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: '<%= ENV['DB_PASSWORD'] %>'
    adapter: postgis
    port: 5432
    encoding: utf8

test:
  primary:
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['DB_DATABASE'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: '<%= ENV['DB_PASSWORD'] %>'
    adapter: trilogy
    port: 3306
  other:
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['DB_DATABASE'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: '<%= ENV['DB_PASSWORD'] %>'
    adapter: postgis
    port: 5432
    encoding: utf8

```
