### ISSUE TITLE
PG::Error: ERROR:  relation "geometry_columns" does not exist

### ISSUE THREAD

**Issue by jure** [rgeo/activerecord-postgis-adapter#47]
I was trying to get PostGIS 2.0.2 working with PostgreSQL 9.2.2 and this adapter and it was not working, even though I followed the tutorial to the dot. At first I thought it was my completely my fault but even though I removed PostGIS and all its remnants and reinstalled it, I was still getting this error with `rake db:create`

```
PG::Error: ERROR:  relation "geometry_columns" does not exist
: ALTER TABLE geometry_columns OWNER TO username
/Users/username/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:652:in `async_exec'
```

After a long while, I decided to try with the latest master, which works splendidly.

This is my database.yml:

```
development:
  adapter: postgis
  schema_search_path: "public,postgis,topology"
  su_username: postgres
  su_password: postgres
  encoding: unicode
  database: database_development
  pool: 5
  timeout: 5000
  username: user
  password: user
  host: localhost
  postgis_extension: "postgis,postgis_topology"
```

Is there anything in the latest release gem that prevents this setup from working?
