### ISSUE TITLE
rake db:create fails to generate spatial_ref_sys table

### ISSUE THREAD

**Issue by nickahoy** [rgeo/activerecord-postgis-adapter#48]
### postgres info

`SELECT version();`
`PostgreSQL 9.2.2 on x86_64-apple-darwin12.2.0, compiled by Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn), 64-bit`

`SELECT postgis_full_version();`
`POSTGIS="2.0.2 r10789" GEOS="3.3.6-CAPI-1.7.6" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.9.2, released 2012/10/08" LIBXML="2.7.8" LIBJSON="UNKNOWN" RASTER`
### gem versions

```
ruby 1.9.3p374
rails (3.2.11)
pg (0.14.1)
activerecord-postgis-adapter (0.5.1)
rgeo (0.3.20)
rgeo-activerecord (0.4.6)
```
### database.yml

``` yml
development:
  adapter: postgis
  encoding: unicode
  database: geo_api_development
  pool: 5
  username: geo_api
  password: u_password
  su_username: postgres
  su_password: su_password
  schema_search_path: "public,postgis,topology"
  postgis_extension: "postgis,postgis_topology"
```
### details

`rake db:create` correctly generates the `postgis` and `postgis_topology` database extensions but does not generate the `spatial_ref_sys` table.

Replacing `postgis_extension: "postgis,postgis_topology"` with `script_dir: /usr/local/share/postgis` (the script location when postgis is installed using `homebrew`) actually fails completely --- no postgis extensions are installed. The scripts directory contains all the usual postgis scripts: `postgis.sql`, `topology.sql`, `spatial_ref_sys.sql` etc.

Running `CREATE EXTENSION postgis;` and `CREATE EXTENSION postgis_topology;` on the database directly with `psql` correctly generates the extensions and the spatial_ref_sys table. 

Note that this is not a full-stack rails application — it was generated using the [rails-api gem](https://github.com/rails-api/rails-api), which creates an app that includes only those modules necessary for creating an api service. If `activerecord-postgis-adapter` depends on any modules that aren't included in this reduced stack then it fails to generate any warnings or errors indicating so. 

If you need any more info, let me know.
